// Auto-generated by scripts/generate-registry.cjs
import en from "./en.json";
import pt_BR from "./pt-BR.json";

export const localeResources: Record<string, { translation: Record<string, string> }> = {
  "en": { translation: en },
  "pt-BR": { translation: pt_BR },
} as const;

export type LocaleCode = keyof typeof localeResources;
