#!/usr/bin/env node
const fs = require("fs");
const path = require("path");

const SRC_DIR = path.join(__dirname, "..", "src/locales");
const PT_BR_PATH = path.join(SRC_DIR, "pt-BR.json");

const LANGUAGES = [
  { code: "pt-BR", name: "Portuguese (Brazil)", native: "Português (Brasil)" },
  { code: "en", name: "English", native: "English" },
  { code: "es", name: "Spanish", native: "Español" },
  { code: "fr", name: "French", native: "Français" },
  { code: "de", name: "German", native: "Deutsch" },
  { code: "it", name: "Italian", native: "Italiano" },
  { code: "nl", name: "Dutch", native: "Nederlands" },
  { code: "pt", name: "Portuguese", native: "Português" },
  { code: "ru", name: "Russian", native: "Русский" },
  { code: "zh", name: "Chinese (Simplified)", native: "简体中文" },
  { code: "zh-TW", name: "Chinese (Traditional)", native: "繁體中文" },
  { code: "ja", name: "Japanese", native: "日本語" },
  { code: "ko", name: "Korean", native: "한국어" },
  { code: "ar", name: "Arabic", native: "العربية" },
  { code: "hi", name: "Hindi", native: "हिन्दी" },
  { code: "bn", name: "Bengali", native: "বাংলা" },
  { code: "tr", name: "Turkish", native: "Türkçe" },
  { code: "vi", name: "Vietnamese", native: "Tiếng Việt" },
  { code: "th", name: "Thai", native: "ไทย" },
  { code: "id", name: "Indonesian", native: "Bahasa Indonesia" },
  { code: "ms", name: "Malay", native: "Bahasa Melayu" },
  { code: "tl", name: "Filipino", native: "Filipino" },
  { code: "pl", name: "Polish", native: "Polski" },
  { code: "uk", name: "Ukrainian", native: "Українська" },
  { code: "ro", name: "Romanian", native: "Română" },
  { code: "hu", name: "Hungarian", native: "Magyar" },
  { code: "cs", name: "Czech", native: "Čeština" },
  { code: "el", name: "Greek", native: "Ελληνικά" },
  { code: "he", name: "Hebrew", native: "עברית" },
  { code: "sv", name: "Swedish", native: "Svenska" },
  { code: "no", name: "Norwegian", native: "Norsk" },
  { code: "da", name: "Danish", native: "Dansk" },
  { code: "fi", name: "Finnish", native: "Suomi" },
  { code: "sk", name: "Slovak", native: "Slovenčina" },
  { code: "bg", name: "Bulgarian", native: "Български" },
  { code: "sr", name: "Serbian", native: "Српски" },
  { code: "hr", name: "Croatian", native: "Hrvatski" },
  { code: "lt", name: "Lithuanian", native: "Lietuvių" },
  { code: "lv", name: "Latvian", native: "Latviešu" },
  { code: "et", name: "Estonian", native: "Eesti" },
  { code: "sl", name: "Slovenian", native: "Slovenščina" },
  { code: "ka", name: "Georgian", native: "ქართული" },
  { code: "hy", name: "Armenian", native: "Հայերեն" },
  { code: "az", name: "Azerbaijani", native: "Azərbaycan dili" },
  { code: "kk", name: "Kazakh", native: "Қазақ тілі" },
  { code: "uz", name: "Uzbek", native: "Oʻzbekcha" },
  { code: "ne", name: "Nepali", native: "नेपाली" },
  { code: "si", name: "Sinhala", native: "සිංහල" },
  { code: "my", name: "Burmese", native: "မြန်မာဘာသာ" },
  { code: "km", name: "Khmer", native: "ភាសាខ្មែរ" },
  { code: "lo", name: "Lao", native: "ລາວ" },
  { code: "mn", name: "Mongolian", native: "Монгол" },
  { code: "am", name: "Amharic", native: "አማርኛ" },
  { code: "sw", name: "Swahili", native: "Kiswahili" },
  { code: "af", name: "Afrikaans", native: "Afrikaans" },
  { code: "ca", name: "Catalan", native: "Català" },
  { code: "gl", name: "Galician", native: "Galego" },
  { code: "eu", name: "Basque", native: "Euskara" },
  { code: "bs", name: "Bosnian", native: "Bosanski" },
  { code: "sq", name: "Albanian", native: "Shqip" },
  { code: "mk", name: "Macedonian", native: "Македонски" },
  { code: "fa", name: "Persian", native: "فارسی" },
  { code: "ur", name: "Urdu", native: "اردو" },
  { code: "ta", name: "Tamil", native: "தமிழ்" },
  { code: "te", name: "Telugu", native: "తెలుగు" },
  { code: "mr", name: "Marathi", native: "मराठी" },
  { code: "gu", name: "Gujarati", native: "ગુજરાતી" },
  { code: "kn", name: "Kannada", native: "ಕನ್ನಡ" },
  { code: "ml", name: "Malayalam", native: "മലയാളം" },
  { code: "pa", name: "Punjabi", native: "ਪੰਜਾਬੀ" },
  { code: "or", name: "Odia", native: "ଓଡ଼ିଆ" },
  { code: "as", name: "Assamese", native: "অসমীয়া" },
  { code: "sd", name: "Sindhi", native: "سنڌي" },
  { code: "bo", name: "Tibetan", native: "བོད་སྐད" },
  { code: "dz", name: "Dzongkha", native: "རྫོང་ཁ" },
  { code: "fy", name: "Frisian", native: "Frysk" },
  { code: "ga", name: "Irish", native: "Gaeilge" },
  { code: "gd", name: "Scottish Gaelic", native: "Gàidhlig" },
  { code: "cy", name: "Welsh", native: "Cymraeg" },
  { code: "mt", name: "Maltese", native: "Malti" },
  { code: "is", name: "Icelandic", native: "Íslenska" },
  { code: "lb", name: "Luxembourgish", native: "Lëtzebuergesch" },
  { code: "mg", name: "Malagasy", native: "Malagasy" },
  { code: "ny", name: "Chichewa", native: "Chichewa" },
  { code: "ha", name: "Hausa", native: "Hausa" },
  { code: "yo", name: "Yoruba", native: "Yorùbá" },
  { code: "ig", name: "Igbo", native: "Igbo" },
  { code: "zu", name: "Zulu", native: "isiZulu" },
  { code: "xh", name: "Xhosa", native: "isiXhosa" },
  { code: "st", name: "Sesotho", native: "Sesotho" },
  { code: "tn", name: "Tswana", native: "Setswana" },
  { code: "rw", name: "Kinyarwanda", native: "Ikinyarwanda" },
  { code: "sn", name: "Shona", native: "chiShona" },
  { code: "so", name: "Somali", native: "Soomaali" },
  { code: "ti", name: "Tigrinya", native: "ትግርኛ" },
  { code: "ku", name: "Kurdish", native: "Kurdî" },
  { code: "ps", name: "Pashto", native: "پښتو" },
  { code: "jw", name: "Javanese", native: "Basa Jawa" },
  { code: "su", name: "Sundanese", native: "Basa Sunda" },
  { code: "ceb", name: "Cebuano", native: "Cebuano" },
  { code: "hmn", name: "Hmong", native: "Hmoob" },
  { code: "co", name: "Corsican", native: "Corsu" },
  { code: "ht", name: "Haitian Creole", native: "Kreyòl Ayisyen" },
  { code: "la", name: "Latin", native: "Latina" },
  { code: "mi", name: "Maori", native: "Te Reo Māori" },
  { code: "sm", name: "Samoan", native: "Gagana Samoa" },
  { code: "haw", name: "Hawaiian", native: "ʻŌlelo Hawaiʻi" },
  { code: "yi", name: "Yiddish", native: "ייִדיש" },
];

const API_URL = process.env.TRANSLATION_API_URL || "";
const MODEL = process.env.TRANSLATION_MODEL || "falcon3";
const API_KEY = process.env.TRANSLATION_API_KEY || "";

const PT_EN = {
  "GESTÃO": "MANAGEMENT",
  "CUIDADOS": "CARE",
  "CONFIGURAÇÕES": "SETTINGS",
  "Configurações": "Settings",
  "Configurações do Sistema": "System Settings",
  "Configurações da instância": "Instance Settings",
  "Configurações do HelpDesk": "HelpDesk Settings",
  "Configuração da Assistente": "Assistant Configuration",
  "Configuradas": "Configured",
  "Configure sua assistente para melhor atender sua igreja.": "Configure your assistant to better serve your church.",
  "Configure todas as regras de formação e aulas do curso.": "Configure all course formation rules and classes.",
  "Configure todas as regras de formação e aulas do evento.": "Configure all event formation rules and days.",
  "Configure os dados solicitados e os automáticos de envio.": "Configure the requested data and auto-send settings.",
  "Configure o formulário que será enviado pela assistente virtual para registrar decisões via WhatsApp.": "Configure the form sent by the virtual assistant to register decisions via WhatsApp.",
  "Administrador": "Administrator",
  "Dashboard": "Dashboard",
  "Membros": "Members",
  "Células": "Cells",
  "Célula": "Cell",
  "Célula que faz parte": "Cell they belong to",
  "Célula:": "Cell:",
  "Células Ativas": "Active Cells",
  "Células ativas": "Active cells",
  "Cursos": "Courses",
  "Curso": "Course",
  "Curso / Aula": "Course / Class",
  "Curso é pago?": "Is the course paid?",
  "Cursos e Cultos": "Courses & Worship",
  "Eventos": "Events",
  "Evento": "Event",
  "Evento / Dia": "Event / Day",
  "Evento é pago?": "Is the event paid?",
  "Eventos e Cultos": "Events & Worship",
  "Atendimentos": "Services",
  "Atendimento": "Service",
  "Atendimentos ativos": "Active services",
  "Atendimentos:": "Services:",
  "Atendido": "Attended",
  "Atendido por:": "Attended by:",
  "Atendidos": "Attended",
  "Atendente": "Attendant",
  "Atendente atual:": "Current attendant:",
  "Atendente: Ana Souza": "Attendant: Ana Souza",
  "Relatórios": "Reports",
  "Relatório": "Report",
  "Relatórios recentes": "Recent reports",
  "Usuários": "Users",
  "Configurações": "Settings",
  "Perfil": "Profile",
  "Perfis da Célula": "Cell Profiles",
  "Perfil das Células": "Cell Profiles",
  "Informações do Perfil": "Profile Information",
  "Informações do perfil": "Profile information",
  "Motivo do perfil": "Profile reason",
  "Novo perfil da célula": "New cell profile",
  "Perfil da Assistente": "Assistant Profile",
  "Help": "Help",
  "Ajuda com os filtros": "Help with filters",
  "Home": "Home",
  "Início": "Home",
  "Basiléia": "Basiléia",
  "Basileia": "Basileia",
  "Basileia Church": "Basileia Church",
  "Basileia Finance": "Basileia Finance",
  "Basileia Help": "Basileia Help",
  "BASILÉIA": "BASILEIA",
  "BASILÉIA LTDA": "BASILEIA LTDA",
  "Basiléia não se responsabiliza": "Basiléia is not responsible",
  "Church OS": "Church OS",
  "CHURCH OS": "CHURCH OS",
  "Igreja": "Church",
  "Igreja do Teste BASILÉIA": "BASILÉIA Test Church",
  "Nome da igreja": "Church name",
  "Nome da igreja anterior": "Previous church name",
  "Conta da igreja": "Church Account",
  "Pastor": "Pastor",
  "Pastor Responsável": "Responsible Pastor",
  "Pastor Responsável:": "Responsible Pastor:",
  "Pastor de rede": "Network pastor",
  "Pastores": "Pastors",
  "Pr. João Silva": "Pr. João Silva",
  "Pr. Lucas Ferreira": "Pr. Lucas Ferreira",
  "Líder": "Leader",
  "Líder do ministério": "Ministry leader",
  "Liderança": "Leadership",
  "Liderança Nível 1": "Leadership Level 1",
  "Membro": "Member",
  "Membro Ativo": "Active Member",
  "Membro Oficial": "Official Member",
  "Membro desde": "Member since",
  "Novo membro": "New member",
  "Editar membro": "Edit member",
  "Buscar membro...": "Search member...",
  "Importar membro": "Import member",
  "Histórico do membro": "Member history",
  "Nome do membro": "Member name",
  "Nome do Membro": "Member Name",
  "Adicionar membro": "Add member",
  "Cadastre um novo membro da sua igreja.": "Register a new member of your church.",
  "Cadastre e gerencie os membros da sua igreja.": "Register and manage your church members.",
  "Visitante": "Visitor",
  "Visitantes": "Visitors",
  "Visitantes Mensais": "Monthly Visitors",
  "Visitantes no mês": "Visitors this month",
  "Novo visitante": "New visitor",
  "Adicionar visitante": "Add visitor",
  "Nome do visitante": "Visitor name",
  "Nome do Visitante": "Visitor Name",
  "Cadastre um novo visitante da sua igreja.": "Register a new visitor of your church.",
  "Cadastre e acompanhe os visitantes da sua igreja.": "Register and track your church visitors.",
  "Registrar novo visitante": "Register new visitor",
  "Selecionar visitante": "Select visitor",
  "Ministério": "Ministry",
  "Ministérios": "Ministries",
  "Nome do ministério": "Ministry name",
  "Novo ministério": "New ministry",
  "Informações do ministério": "Ministry information",
  "Líder do ministério": "Ministry leader",
  "Cadastre um novo ministério e vincule seu líder responsável.": "Register a new ministry and link its responsible leader.",
  "Cadastre e gerencie os ministérios e seus respectivos líderes.": "Register and manage ministries and their respective leaders.",
  "Rede": "Network",
  "Redes": "Networks",
  "Rede Esperança": "Hope Network",
  "Rede Sem Fronteiras": "Network Without Borders",
  "Rede que faz parte": "Network they belong to",
  "Rede:": "Network:",
  "Nome da Rede": "Network Name",
  "Nome da rede": "Network name",
  "Nova rede": "New network",
  "Informações da Rede": "Network Information",
  "Informações da rede": "Network information",
  "Buscar rede...": "Search network...",
  "Cadastre uma nova rede e vincule seu pastor responsável.": "Register a new network and link its responsible pastor.",
  "Gerencie as redes da igreja.": "Manage church networks.",
  "Culto": "Worship",
  "Cultos": "Worship",
  "Agenda de Cultos": "Worship Schedule",
  "Tema do Culto": "Worship Theme",
  "Presença último culto": "Last worship attendance",
  "Frequência dos cultos": "Worship frequency",
  "Cadastre e gerencie os horários dos cultos da sua igreja.": "Register and manage your church worship times.",
  "Serviço": "Service",
  "Controle de Presença": "Attendance Control",
  "Controle de Presença - Acampamento Jovem": "Attendance Control - Youth Camp",
  "Controle de Presença - Cursos": "Attendance Control - Courses",
  "Controle de Presença - Eventos": "Attendance Control - Events",
  "Controle de Presença - Liderança Nível 1": "Attendance Control - Leadership Level 1",
  "Registro de Presença": "Attendance Record",
  "Novo Registro de Presença": "New Attendance Record",
  "Presença 3m": "Attendance 3m",
  "Presença média": "Average attendance",
  "Presenças": "Attendances",
  "Oferecimento": "Offering",
  "Oração": "Prayer",
  "Pedido de oração": "Prayer request",
  "Pedidos de Oração": "Prayer Requests",
  "Fila de oração": "Prayer queue",
  "Equipe de Oração": "Prayer Team",
  "Batismo": "Baptism",
  "Batismo:": "Baptism:",
  "Batizado?": "Baptized?",
  "Data do batismo": "Baptism date",
  "Aceitou Jesus": "Accepted Jesus",
  "Aceitou Jesus?": "Accepted Jesus?",
  "Data que aceitou Jesus": "Date accepted Jesus",
  "Quantas pessoas aceitaram Jesus": "How many people accepted Jesus",
  "Decisões por Jesus": "Decisions for Jesus",
  "Evangelismo": "Evangelism",
  "Nome": "Name",
  "Nome completo": "Full name",
  "Nome Completo": "Full Name",
  "Nome de usuário": "Username",
  "Nome da Agente": "Agent Name",
  "Nome da Célula": "Cell Name",
  "Nome da Pessoa": "Person's Name",
  "Nome do Aluno": "Student Name",
  "Nome do Curso / Evento": "Course / Event Name",
  "Nome do Evento": "Event Name",
  "Nome do Participante": "Participant Name",
  "Nome do Perfil": "Profile Name",
  "Nome do relatório": "Report name",
  "Nome no cartão": "Name on card",
  "E-mail": "Email",
  "E-mail (Login)": "Email (Login)",
  "E-mail de acesso": "Access email",
  "Buscar por E-mail": "Search by Email",
  "Telefone": "Phone",
  "Telefone / WhatsApp": "Phone / WhatsApp",
  "Celular / Recado": "Mobile / Message",
  "Endereço": "Address",
  "Endereço Completo": "Full Address",
  "Endereço, célula, redes e histórico.": "Address, cell, networks and history.",
  "Cidade": "City",
  "Estado": "State",
  "País": "Country",
  "Bairro": "Neighborhood",
  "CEP": "ZIP Code",
  "Rua": "Street",
  "Rua / Logradouro": "Street / Address",
  "Número": "Number",
  "Complemento": "Complement",
  "Data": "Date",
  "Data da Aula": "Class Date",
  "Data da aula": "Class date",
  "Data da Presença": "Attendance Date",
  "Data de Divulgação": "Announcement Date",
  "Data de início": "Start date",
  "Data de nascimento": "Date of birth",
  "Data do Evento": "Event Date",
  "Data do encontro": "Meeting date",
  "Data do evento": "Event date",
  "Data e hora ↓": "Date and time ↓",
  "Data final": "End date",
  "Data fundação": "Foundation date",
  "Data inicial": "Start date",
  "Data de casamento": "Wedding date",
  "Data de entrada:": "Entry date:",
  "Data de inicio": "Start date",
  "Data/Hora Inicial": "Start Date/Time",
  "Horário": "Time",
  "Horário de encontro": "Meeting time",
  "Horário de início": "Start time",
  "Horário de término": "End time",
  "Horário do contato": "Contact time",
  "Status": "Status",
  "Status do Usuário": "User Status",
  "Status do acompanhamento": "Follow-up status",
  "Status da Equipe": "Team Status",
  "Status Oração": "Prayer Status",
  "Ativo": "Active",
  "Inativo": "Inactive",
  "Tipo": "Type",
  "Tipo de Resposta": "Answer Type",
  "Tipo de resposta": "Answer type",
  "Categoria": "Category",
  "Categoria / Tag": "Category / Tag",
  "Categoria detectada: Pedido de oração": "Detected category: Prayer request",
  "Categoria:": "Category:",
  "Categorias": "Categories",
  "Categorias de Atendimento": "Service Categories",
  "Descrição": "Description",
  "Descrição (opcional)": "Description (optional)",
  "Descrição do cargo": "Role description",
  "Observações": "Notes",
  "Observações do perfil": "Profile notes",
  "Anotação interna:": "Internal note:",
  "Nova anotação": "New note",
  "Adicione notas adicionais sobre o membro...": "Add additional notes about the member...",
  "Notas": "Notes",
  "Criar": "Create",
  "Criar Novo QR Code": "Create New QR Code",
  "Criar Novo Relatório": "Create New Report",
  "Criado em": "Created on",
  "Atualizar": "Update",
  "Atualizar assinatura": "Update subscription",
  "Atualizar curso": "Update course",
  "Atualizar célula": "Update cell",
  "Atualizar evento": "Update event",
  "Atualize as informações básicas de acesso da conta da igreja.": "Update the basic access information of the church account.",
  "Atualize os dados do membro.": "Update member data.",
  "Deletar": "Delete",
  "Excluir": "Delete",
  "Exclui um valor específico do seu relatório.": "Excludes a specific value from your report.",
  "Visualizar": "View",
  "Visualize e gerencie os registros de presença dos cultos da sua igreja.": "View and manage your church worship attendance records.",
  "Visualize e gerencie os registros recebidos via WhatsApp pela assistente virtual.": "View and manage records received via WhatsApp by the virtual assistant.",
  "Editar": "Edit",
  "Editar contato": "Edit contact",
  "Edite o cronograma caso haja imprevistos/feriados:": "Edit the schedule in case of unforeseen events/holidays:",
  "Listar": "List",
  "Buscar": "Search",
  "Buscar campo...": "Search field...",
  "Buscar categoria...": "Search category...",
  "Buscar conversa, telefone ou etiqueta...": "Search conversation, phone or tag...",
  "Buscar curso por nome": "Search course by name",
  "Buscar célula...": "Search cell...",
  "Buscar evento por nome": "Search event by name",
  "Buscar membros, células, eventos...": "Search members, cells, events...",
  "Buscar por CPF/CNPJ": "Search by Tax ID",
  "Buscar por E-mail": "Search by Email",
  "Buscar por Líder": "Search by Leader",
  "Buscar por Nome": "Search by Name",
  "Buscar por Nome da Rede": "Search by Network Name",
  "Buscar por Papel/Perfil": "Search by Role/Profile",
  "Buscar por Pastor": "Search by Pastor",
  "Buscar por Perfil": "Search by Profile",
  "Buscar por assunto": "Search by subject",
  "Buscar por descrição": "Search by description",
  "Buscar por nome ou líder": "Search by name or leader",
  "Buscar por nome, telefone ou protocolo...": "Search by name, phone or protocol...",
  "Buscar por nome, telefone, célula ou rede": "Search by name, phone, cell or network",
  "Buscar por solicitante": "Search by requester",
  "Buscar por tipo": "Search by type",
  "Buscar relatórios...": "Search reports...",
  "Pesquisar...": "Search...",
  "Pesquisar aula...": "Search class...",
  "Pesquisar curso ou aula": "Search course or class",
  "Pesquisar dia...": "Search day...",
  "Pesquisar evento ou dia": "Search event or day",
  "Pesquisar no histórico...": "Search history...",
  "Pesquisar nome ou WhatsApp...": "Search name or WhatsApp...",
  "Pesquisar registro...": "Search record...",
  "Filtrar": "Filter",
  "Filtros": "Filters",
  "Adicionar": "Add",
  "Adicionar Regra": "Add Rule",
  "Adicionar aluno": "Add student",
  "Adicionar etiqueta": "Add tag",
  "Adicionar inscrito": "Add enrollee",
  "Adicionar novo líder": "Add new leader",
  "Adicionar opção": "Add option",
  "Adicionar outra opção": "Add another option",
  "Adicionar participante": "Add participant",
  "Adicionar perfil!": "Add profile!",
  "Adicionar pergunta": "Add question",
  "Novo": "New",
  "Novo Curso": "New Course",
  "Novo Evento": "New Event",
  "Novo QR Code": "New QR Code",
  "Novo cargo": "New role",
  "Novo curso": "New course",
  "Novo evento": "New event",
  "Novo horário": "New time",
  "Novo ministério": "New ministry",
  "Novo registro": "New record",
  "Novo relatório": "New report",
  "Novo usuário": "New user",
  "Nova Categoria": "New Category",
  "Nova conexão": "New connection",
  "Nova célula": "New cell",
  "Nova lista de presença": "New attendance list",
  "Nova rede": "New network",
  "Nova senha": "New password",
  "Remover": "Remove",
  "Remover Anexo": "Remove Attachment",
  "Remover horário": "Remove time",
  "Remover opção": "Remove option",
  "Fechar": "Close",
  "Voltar": "Back",
  "Voltar para Redes": "Back to Networks",
  "Voltar para o Curso": "Back to Course",
  "Voltar para o Evento": "Back to Event",
  "Voltar para registros": "Back to records",
  "Voltar ao dashboard": "Back to dashboard",
  "Próximo": "Next",
  "Próxima": "Next",
  "Próximo Evento": "Next Event",
  "Anterior": "Previous",
  "Submit": "Submit",
  "Confirmar": "Confirm",
  "Confirmar desativação": "Confirm deactivation",
  "Confirmar nova senha": "Confirm new password",
  "Salvar": "Save",
  "Salvar alterações": "Save changes",
  "Salvar membro": "Save member",
  "SALVAR ALTERAÇÕES": "SAVE CHANGES",
  "SALVAR E CONCLUIR": "SAVE AND FINISH",
  "Carregando...": "Loading...",
  "Erro": "Error",
  "Sucesso": "Success",
  "Aviso:": "Warning:",
  "Aviso: A plataforma": "Warning: The platform",
  "Atenção:": "Attention:",
  "Atenção: Apenas 1 QR Code por finalidade é permitido.": "Attention: Only 1 QR Code per purpose is allowed.",
  "Informação": "Information",
  "Informações Adicionais": "Additional Information",
  "Informações Básicas": "Basic Information",
  "Informações Opcionais": "Optional Information",
  "Informações da célula": "Cell information",
  "Informações do cargo": "Role information",
  "Informações Básicas do Curso": "Basic Course Information",
  "Informações Básicas do Evento": "Basic Event Information",
  "Nenhum resultado encontrado": "No results found",
  "Nenhum registro encontrado": "No records found",
  "Nenhum QR Code encontrado": "No QR Code found",
  "Nenhum campo encontrado": "No field found",
  "Nenhum curso selecionado": "No course selected",
  "Nenhum evento selecionado": "No event selected",
  "Nenhum histórico encontrado": "No history found",
  "Nenhum horário cadastrado": "No registered times",
  "Nenhum atendimento finalizado nesta busca.": "No completed services in this search.",
  "Nenhuma coluna selecionada": "No column selected",
  "Nenhuma configuração encontrada": "No configuration found",
  "Nenhuma célula selecionada": "No cell selected",
  "Nenhuma pergunta extra adicionada.": "No extra questions added.",
  "Selecione": "Select",
  "Selecione uma opção": "Select an option",
  "Selecione a finalidade": "Select the purpose",
  "Selecione a rede": "Select the network",
  "Selecione o evento/curso": "Select the event/course",
  "Selecione o líder responsável": "Select the responsible leader",
  "Selecione o pastor responsável": "Select the responsible pastor",
  "Selecione o perfil": "Select the profile",
  "Selecione o responsável pela rede": "Select the network responsible",
  "Selecione o responsável pelo ministério": "Select the ministry responsible",
  "Selecione o sexo": "Select gender",
  "Selecione o tipo": "Select the type",
  "Selecione os campos na lista ao lado para compor o seu relatório.": "Select the fields in the list to compose your report.",
  "Selecione os campos que deseja incluir no seu relatório.": "Select the fields you want to include in your report.",
  "Selecione para carregar a lista": "Select to load the list",
  "Selecione um curso no campo acima para carregar a lista completa de alunos matriculados nesta turma.": "Select a course above to load the full student list for this class.",
  "Selecione um evento no campo acima para carregar a lista completa de inscritos neste evento.": "Select an event above to load the full enrollee list for this event.",
  "Selecione um ou mais ministérios...": "Select one or more ministries...",
  "Selecione uma célula no campo acima para carregar a lista completa de membros e visitantes vinculados a ela.": "Select a cell above to load all members and visitors linked to it.",
  "Selecionar aluno": "Select student",
  "Selecionar aluno para reposição": "Select student for replacement",
  "Selecionar cônjuge": "Select spouse",
  "Selecionar membro": "Select member",
  "Selecionar participante": "Select participant",
  "Selecionar participante avulso": "Select individual participant",
  "Selecionar todos": "Select all",
  "Selecionado": "Selected",
  "Tem certeza que deseja converter o visitante": "Are you sure you want to convert the visitor",
  "Campo obrigatório": "Required field",
  "Campos obrigatórios para salvar.": "Required fields to save.",
  "Campos obrigatórios para salvar o membro.": "Required fields to save the member.",
  "Formato inválido": "Invalid format",
  "Importar": "Import",
  "IMPORTAR CÉLULA": "IMPORT CELL",
  "Exportar": "Export",
  "Exportar CSV": "Export CSV",
  "Exportar Excel": "Export Excel",
  "Exportar PDF": "Export PDF",
  "Exportação de Relatórios": "Report Export",
  "Imprimir": "Print",
  "Enviar": "Send",
  "Enviar arquivo": "Upload file",
  "Enviar logo": "Send logo",
  "Enviadas hoje": "Sent today",
  "Receber": "Receive",
  "Recebidos via WhatsApp": "Received via WhatsApp",
  "Confirmar": "Confirm",
  "Senha": "Password",
  "Senha atual": "Current password",
  "Senha de acesso": "Access password",
  "Nova senha": "New password",
  "Cargo": "Role",
  "Cargos": "Roles",
  "Novo cargo": "New role",
  "Descrição do cargo": "Role description",
  "Informações do cargo": "Role information",
  "Cadastre um novo cargo ou função da sua igreja.": "Register a new role or position for your church.",
  "Cadastre e gerencie os cargos e funções da sua igreja.": "Register and manage positions and roles for your church.",
  "Função": "Function",
  "Função específica": "Specific function",
  "Cadastros": "Registration",
  "Cadastro e Gerenciamento": "Registration and Management",
  "Cadastre e organize as perguntas que serão feitas pela assistente virtual.": "Register and organize the questions asked by the virtual assistant.",
  "Cadastre um novo perfil para participação nas células da igreja.": "Register a new profile for participation in church cells.",
  "Cadastre um novo usuário para acesso ao sistema.": "Register a new user for system access.",
  "Cadastre uma nova célula e organize participantes e liderança.": "Register a new cell and organize participants and leadership.",
  "Ações": "Actions",
  "Ação": "Action",
  "Ações Prioritárias": "Priority Actions",
  "Ações prioritárias de hoje": "Today's priority actions",
  "Ações rápidas": "Quick actions",
  "Modalidade": "Modality",
  "Módulo": "Module",
  "Módulos": "Modules",
  "Sobre": "About",
  "Sobre as notificações": "About notifications",
  "Sobre os registros": "About records",
  "Aplicar": "Apply",
  "Limpar": "Clear",
  "Todos": "All",
  "Todas (24)": "All (24)",
  "Todos Gestores": "All Managers",
  "Todos Líderes": "All Leaders",
  "Todos os status": "All statuses",
  "Total": "Total",
  "Total Atendimentos": "Total Services",
  "Total de instâncias": "Total instances",
  "Total de registros": "Total records",
  "Total de respostas:": "Total responses:",
  "Mostrando": "Showing",
  "Mostrando 5 de 5 relatórios": "Showing 5 of 5 reports",
  "Mostrando 7 de 7 relatórios": "Showing 7 of 7 reports",
  "Mostrando resultados": "Showing results",
  "Página": "Page",
  "Linhas por página": "Rows per page",
  "10 por página": "10 per page",
  "20 por página": "20 per page",
  "Ativar": "Activate",
  "Atribuir Responsáveis": "Assign Responsibles",
  "Sincronizar": "Sync",
  "Baixar": "Download",
  "Baixar QR Code": "Download QR Code",
  "Gerar": "Generate",
  "Gerar Aulas": "Generate Classes",
  "Gerar Dias": "Generate Days",
  "Gerar QR Code": "Generate QR Code",
  "Gerar Relatório": "Generate Report",
  "Gerar relatório": "Generate report",
  "Gere e baixe relatórios consolidados em Excel ou PDF do HelpDesk.": "Generate and download consolidated Excel or PDF reports from HelpDesk.",
  "Gere o QR Code": "Generate the QR Code",
  "Gerado por": "Generated by",
  "Gerenciamento de Células": "Cell Management",
  "Gerencie a lista de presença das aulas desta turma específica.": "Manage the attendance list for this specific class.",
  "Gerencie a lista de presença por dia de evento desta turma específica.": "Manage the attendance list per event day for this specific class.",
  "Gerencie as categorias, filas e os tempos limites de resposta (SLA) para cada tipo de solicitação.": "Manage categories, queues and response time limits (SLA) for each request type.",
  "Gerencie as listas de presença das aulas dos cursos da igreja.": "Manage attendance lists for church course classes.",
  "Gerencie as listas de presença e check-in dos eventos da igreja.": "Manage attendance lists and check-in for church events.",
  "Gerencie as pessoas que aceitaram Jesus através": "Manage people who accepted Jesus through",
  "Gerencie as preferências e relatórios do módulo de atendimento.": "Manage preferences and reports for the service module.",
  "Gerencie os QR Codes que iniciam automações via WhatsApp, acompanhe acessos e respostas.": "Manage QR Codes that start WhatsApp automations, track access and responses.",
  "Gerencie os cursos e treinamentos ministeriais.": "Manage courses and ministerial training.",
  "Gerencie os dados institucionais, idioma e endereço da sua igreja.": "Manage institutional data, language and address of your church.",
  "Gerencie os eventos e retiros da igreja.": "Manage church events and retreats.",
  "Gerencie os usuários e permissões de acesso ao sistema.": "Manage users and system access permissions.",
  "Gerencie quais tipos de notificação a assistente virtual pode enviar.": "Manage which notification types the virtual assistant can send.",
  "Gerencie suas instâncias do WhatsApp, acompanhe o uso e o propósito das notificações.": "Manage your WhatsApp instances, track usage and notification purpose.",
  "Gerencie todas as células da igreja.": "Manage all church cells.",
  "Gerencie todas as preferências, integrações e segurança da sua igreja.": "Manage all preferences, integrations and security for your church.",
  "QR Code": "QR Code",
  "QR Codes": "QR Codes",
  "QR Codes ativos": "Active QR Codes",
  "Assistente Virtual": "Virtual Assistant",
  "A assistente será exibida para os membros conforme as configurações definidas.": "The assistant will be displayed to members according to the configured settings.",
  "A assistente virtual utiliza estes tipos de notificação para se comunicar com os membros da igreja.": "The virtual assistant uses these notification types to communicate with church members.",
  "Prévia da Assistente": "Assistant Preview",
  "Contato": "Contact",
  "Contato desde 12/03/2024": "Contact since 03/12/2024",
  "Contato para acompanhamento": "Contact for follow-up",
  "Chat": "Chat",
  "Conversar no WhatsApp": "Chat on WhatsApp",
  "Conversas Ativas (Supervisão)": "Active Conversations (Supervision)",
  "Logs": "Logs",
  "Logs e Histórico": "Logs and History",
  "Alertas (Log)": "Alerts (Log)",
  "Notificação": "Notification",
  "Notificações de Aniversários": "Birthday Notifications",
  "Notificações de Culto": "Worship Notifications",
  "Notificações de Cursos": "Course Notifications",
  "Notificações de Células": "Cell Notifications",
  "Notificações de Eventos": "Event Notifications",
  "TIPO DE NOTIFICAÇÃO": "NOTIFICATION TYPE",
  "Tipos de Notificação": "Notification Types",
  "Notificar Membros": "Notify Members",
  "Notificar Visitantes": "Notify Visitors",
  "Instâncias ativas": "Active instances",
  "Instâncias do WhatsApp": "WhatsApp Instances",
  "Nome da instância": "Instance name",
  "Configurações da instância": "Instance Settings",
  "WhatsApp": "WhatsApp",
  "Abra o WhatsApp": "Open WhatsApp",
  "Idioma": "Language",
  "Língua preferida": "Preferred language",
  "Selecione a língua preferida para resposta e comunicação com a assistente virtual": "Select your preferred language for responses and communication with the virtual assistant",
  "Tradução": "Translation",
  "Versão": "Version",
  "Versão da Bíblia": "Bible Version",
  "Identidade da igreja": "Church Identity",
  "História da Igreja": "Church History",
  "Estrutura Hierárquica": "Hierarchical Structure",
  "Hierarquia e Pessoas": "Hierarchy and People",
  "Dados de acesso": "Access data",
  "Dados do atendimento": "Service data",
  "Dados Bancários": "Banking Data",
  "Dados complementares para o cadastro.": "Additional data for registration.",
  "Dados essenciais para o cadastro.": "Essential data for registration.",
  "Detalhes sobre o perfil e contatos do membro.": "Details about the member's profile and contacts.",
  "Acompanhe e organize os atendimentos registrados no sistema.": "Track and organize the services registered in the system.",
  "Acompanhe todas as alterações, interações, movimentações e registros relacionados a este membro.": "Track all changes, interactions, movements and records related to this member.",
  "Acompanhe todas as atividades, alterações e interações registradas no sistema.": "Track all activities, changes and interactions recorded in the system.",
  "Acompanhe todos as aulas já realizadas por este curso.": "Track all classes already completed for this course.",
  "Acompanhe todos os dias já realizados deste evento.": "Track all days already completed for this event.",
  "Acompanhe todos os encontros já realizados por esta célula.": "Track all meetings already held by this cell.",
  "Histórico de Atendidos": "Attended History",
  "Histórico de Registro": "Record History",
  "Histórico rápido": "Quick history",
  "Resumo do histórico": "History summary",
  "Resumo inteligente": "Smart summary",
  "Resumo": "Summary",
  "Ver Histórico": "View History",
  "Ver detalhes": "View details",
  "Ver histórico completo": "View full history",
  "Ver relatório completo": "View full report",
  "Ver todas": "View all",
  "VER EM ÁRVORE": "VIEW TREE",
  "VER LISTA DE PESSOAS": "VIEW PEOPLE LIST",
  "Sala de Controle": "Control Room",
  "Painel Gerencial de Atendimentos": "Service Management Panel",
  "Indicadores": "Indicators",
  "Acessos": "Accesses",
  "Acessos hoje": "Today's accesses",
  "Mensagens hoje": "Today's messages",
  "Média Real": "Real Average",
  "Média de Membros": "Average Members",
  "Média": "Average",
  "Frequência": "Frequency",
  "Frequência Média": "Average Frequency",
  "Frequência dos cultos": "Worship frequency",
  "Ranking (Frequência Média)": "Ranking (Average Frequency)",
  "Métricas de Células": "Cell Metrics",
  "Saúde das células": "Cell Health",
  "Performance": "Performance",
  "Tempo Real: Ativo": "Real Time: Active",
  "Supervisão em tempo real da operação do HelpDesk.": "Real-time supervision of HelpDesk operation.",
  "Central de atendimento": "Help center",
  "Controle de atendimento": "Service control",
  "Assumir Atendimento &rarr;": "Take over Service &rarr;",
  "Finalizar atendimento": "Finish service",
  "Transferir": "Transfer",
  "Transferir para outro atendente": "Transfer to another attendant",
  "Intervir": "Intervene",
  "Fila / Categoria": "Queue / Category",
  "Fila de Espera": "Waiting Queue",
  "Fila: Oração": "Queue: Prayer",
  "Conexões": "Connections",
  "Conexões saudáveis": "Healthy connections",
  "Todas as conexões estão funcionando perfeitamente! Nenhuma instabilidade detectada.": "All connections are working perfectly! No instability detected.",
  "Revisar conexões": "Review connections",
  "Conectar aparelho": "Connect device",
  "Aparelho": "Device",
  "Aparelhos conectados": "Connected devices",
  "Como conectar": "How to connect",
  "Uso total": "Total usage",
  "Limite consumido": "Consumed limit",
  "Alerta em 80% do uso": "Alert at 80% usage",
  "Acima de 80%": "Above 80%",
  "2 instâncias com &gt; 80%": "2 instances with &gt; 80%",
  "Com Alerta (2)": "With Alert (2)",
  "Próximas do limite": "Near the limit",
  "Instâncias": "Instances",
  "Etiquetas": "Tags",
  "Adicionar etiqueta": "Add tag",
  "Turma": "Class",
  "Aula": "Class",
  "Aulas": "Classes",
  "Primeira Aula": "First Class",
  "Qtd Aulas": "Num Classes",
  "Duração": "Duration",
  "Data / Duração": "Date / Duration",
  "Alunos Avulsos / Reposição": "Individual Students / Replacement",
  "Alunos Matriculados": "Enrolled Students",
  "Inscritos": "Enrolled",
  "Nº Inscritos": "Enrolled No.",
  "Máximo de Inscritos": "Maximum Enrolled",
  "Participantes Avulsos": "Individual Participants",
  "Participantes Inscritos": "Enrolled Participants",
  "Inscrição": "Enrollment",
  "Inscrições": "Enrollments",
  "Pausar Inscrições?": "Pause Enrollments?",
  "Participante pode cancelar inscrição?": "Can participant cancel enrollment?",
  "Permite visitantes?": "Allows visitors?",
  "Permitir inscrição individual por aula (avulsa)?": "Allow individual enrollment per class?",
  "Permitir inscrição individual por dia (avulsa)?": "Allow individual enrollment per day?",
  "Quando o curso/evento ficará visível para inscrições?": "When will the course/event be visible for enrollments?",
  "Quando o evento ficará visível para inscrições?": "When will the event be visible for enrollments?",
  "Link para pagamento": "Payment link",
  "Inscrições": "Enrollments",
  "Listas de Presença": "Attendance Lists",
  "NOVA LISTA DE PRESENÇA": "NEW ATTENDANCE LIST",
  "NOVA LISTA DA CÉLULA": "NEW CELL LIST",
  "NOVA CÉLULA": "NEW CELL",
  "NOVA REDE": "NEW NETWORK",
  "NOVO PERFIL": "NEW PROFILE",
  "Registre quem esteve presente na aula do curso.": "Record who was present in the course class.",
  "Registre quem esteve presente no dia de evento.": "Record who was present on the event day.",
  "Registre quem esteve presente no encontro da célula.": "Record who was present at the cell meeting.",
  "Registro completo de todas as conversas e atendimentos finalizados.": "Complete record of all conversations and completed services.",
  "Registrar ação": "Register action",
  "Presente?": "Present?",
  "Presentes": "Present",
  "Faltantes": "Absent",
  "Toggle presence": "Toggle presence",
  "FAZER CHAMADA": "TAKE ATTENDANCE",
  "Chamada": "Attendance",
  "Idade": "Age",
  "Idade Final": "End Age",
  "Idade final": "End age",
  "Idade Mínima": "Minimum Age",
  "Idade mínima": "Minimum age",
  "Informe a idade final": "Enter the end age",
  "Informe a idade mínima": "Enter the minimum age",
  "Sexo": "Gender",
  "Masculino": "Male",
  "Feminino": "Female",
  "Estado civil": "Marital status",
  "Casado?": "Married?",
  "Solteiro": "Single",
  "Nacionalidade": "Nationality",
  "Escolaridade": "Education",
  "Profissão": "Profession",
  "É estrangeiro?": "Is foreigner?",
  "Documento (CPF/RG)": "Document (ID)",
  "CPF do titular": "Holder's CPF",
  "CPF/CNPJ": "Tax ID",
  "Razão social": "Legal name",
  "Tem filhos?": "Has children?",
  "Quantidade de filhos": "Number of children",
  "Filhos": "Children",
  "Avançado": "Advanced",
  "Básico": "Basic",
  "Basic": "Basic",
  "Plus": "Plus",
  "Start": "Start",
  "Premium": "Premium",
  "Planos e cobrança": "Plans and billing",
  "Plano Anual": "Annual Plan",
  "Plano Anual:": "Annual Plan:",
  "Plano Mensal": "Monthly Plan",
  "Plano Mensal:": "Monthly Plan:",
  "Mensal (30 dias)": "Monthly (30 days)",
  "Semanal (7 dias)": "Weekly (7 days)",
  "Quinzenal (14 dias)": "Biweekly (14 days)",
  "Assinatura": "Subscription",
  "Vencimento": "Due date",
  "Pagamento": "Payment",
  "Pago": "Paid",
  "Pendente": "Pending",
  "Em atraso": "Overdue",
  "Cartão de crédito": "Credit card",
  "Número do cartão": "Card number",
  "Nome no cartão": "Name on card",
  "MM / AA": "MM / YY",
  "Código de segurança": "Security code",
  "Como está impresso no cartão": "As printed on the card",
  "Hipercard": "Hipercard",
  "Boleto": "Boleto",
  "PIX": "PIX",
  "Cobrança 100% segura": "100% secure payment",
  "Cobrança recorrente mensal. Cancele quando quiser.": "Monthly recurring charge. Cancel anytime.",
  "Consulte condições": "Check conditions",
  "Fale com um especialista": "Speak with a specialist",
  "Parceiro": "Partner",
  "Código de parceiro": "Partner code",
  "Digite o código de parceiro": "Enter the partner code",
  "Use um código de parceiro para obter benefícios.": "Use a partner code to get benefits.",
  "2. Código de parceiro": "2. Partner code",
  "Comunicação": "Communication",
  "Comunicação inteligente": "Smart communication",
  "Controle total": "Full control",
  "Mais organização": "More organization",
  "Melhor distribuição": "Better distribution",
  "Segura & Confiável": "Secure & Reliable",
  "Múltiplas conexões": "Multiple connections",
  "API": "API",
  "API utilizada": "API used",
  "Personalize as informações e o comportamento da sua assistente virtual.": "Customize the information and behavior of your virtual assistant.",
  "Como ela está se chamando?": "What is it called?",
  "Mensagem inicial": "Initial message",
  "Saudação": "Greeting",
  "Veja como sua assistente será apresentada aos membros.": "See how your assistant will be presented to members.",
  "Guia de Navegação": "Navigation Guide",
  "Material de Apoio": "Support Material",
  "Guia, PDF ou Material de boas-vindas": "Guide, PDF or Welcome Material",
  "Link do Google Drive, Dropbox...": "Google Drive, Dropbox link...",
  "Link para o Material": "Material Link",
  "Possui material de apoio (Apostila)?": "Has support material (Workbook)?",
  "Arquivo de apoio (opcional)": "Support file (optional)",
  "Envie uma imagem ou vídeo que será compartilhado junto com o formulário.": "Send an image or video that will be shared along with the form.",
  "Formatos: JPG, PNG, MP4, MOV ou AVI. Dimensões: 1080 x 1350 px. Tamanho máximo: 10MB.": "Formats: JPG, PNG, MP4, MOV or AVI. Dimensions: 1080 x 1350 px. Max size: 10MB.",
  "Formatos permitidos: JPG, GIF ou PNG": "Allowed formats: JPG, GIF or PNG",
  "Logo da igreja": "Church logo",
  "Enviar logo": "Send logo",
  "Dimensões recomendadas: 50 × 200 px": "Recommended dimensions: 50 × 200 px",
  "Tamanho máximo: 800 KB": "Maximum size: 800 KB",
  "Trocar arquivo": "Change file",
  "Aniversário": "Birthday",
  "Data de aniversário": "Birthday date",
  "Calendário": "Calendar",
  "Compromisso": "Appointment",
  "Eventos futuros": "Upcoming events",
  "Eventos passados": "Past events",
  "Acampamento Jovem 2026": "Youth Camp 2026",
  "Retiro de Jovens": "Youth Retreat",
  "Jovens": "Youth",
  "Jovens": "Youth",
  "Ana Souza": "Ana Souza",
  "Ana Souza • 10:23": "Ana Souza • 10:23",
  "João Pedro Silva": "João Pedro Silva",
  "Jonatas Sch.": "Jonatas Sch.",
  "Maria Clara Silva": "Maria Clara Silva",
  "Vinicius Rodrigues": "Vinicius Rodrigues",
  "Olá! Gostaria de pedir oração pela minha mãe.": "Hello! I'd like to ask for prayer for my mother.",
  "Olá, Maria Clara! Paz do Senhor! 🙏": "Hello, Maria Clara! Peace of the Lord! 🙏",
  "O nome dela é Dona Lúcia. A cirurgia é às 15h.": "Her name is Dona Lúcia. The surgery is at 3 PM.",
  "Ela está internada e vamos fazer uma cirurgia hoje à tarde.": "She is hospitalized and will have surgery this afternoon.",
  "Entendi, Maria Clara. Já estamos orando por Dona Lúcia.": "Understood, Maria Clara. We are already praying for Dona Lúcia.",
  "Fique tranquila, Deus está no controle! ✨": "Stay calm, God is in control! ✨",
  "Vamos orar pela sua mãe agora mesmo.": "We will pray for your mother right now.",
  "pediu retorno hoje à noite após a cirurgia.": "asked for a follow-up tonight after the surgery.",
  "Excelente! Uma notificação automática será enviada ao público segmentado avisando sobre estas exceções no cronograma.": "Excellent! An automatic notification will be sent to the targeted audience informing them about these schedule exceptions.",
  "COPYRIGHT © 2026": "COPYRIGHT © 2026",
  ", Todos os direitos reservados": ", All rights reserved",
  "Copyright © 2026 Basiléia, Todos os direitos reservados": "Copyright © 2026 Basiléia, All rights reserved",
  "Meus Sistemas": "My Systems",
  "Gestão eclesiástica": "Church management",
  "Gestão financeira completa": "Complete financial management",
  "Vai ter transmissão online?": "Will there be an online stream?",
  "A transmissão também é paga?": "Is the stream also paid?",
  "Link da Transmissão (Zoom/YouTube)": "Stream Link (Zoom/YouTube)",
  "Tem certificado de conclusão?": "Has completion certificate?",
  "Este curso deve reiniciar as inscrições após a última aula?": "Should this course restart enrollments after the last class?",
  "Este curso tem encontros recorrentes (várias aulas)?": "Does this course have recurring meetings (multiple classes)?",
  "Este evento tem duração de múltiplos dias?": "Does this event span multiple days?",
  "Este evento/curso é pago.": "This event/course is paid.",
  "O sistema de automação de QR Code via WhatsApp não suporta cobrança. Inscrições pagas devem ser feitas por outros canais.": "The QR Code automation system via WhatsApp does not support payments. Paid enrollments must be done through other channels.",
  "pela gestão financeira, bloqueio de vagas por ausência de pagamento, cobranças ou qualquer conciliação bancária de cursos e eventos pagos.": "for financial management, blocking spots due to non-payment, charges or any bank reconciliation for paid courses and events.",
  "pela gestão financeira, bloqueio de vagas por ausência de pagamento, cobranças ou qualquer conciliação bancária de eventos pagos.": "for financial management, blocking spots due to non-payment, charges or any bank reconciliation for paid events.",
  "Precisa apresentar documento?": "Needs to present ID?",
  "Precisa de autorização dos pais?": "Needs parental authorization?",
  "Tem limite de faltas permitidas?": "Has a limit for allowed absences?",
  "Máximo de faltas toleradas": "Maximum tolerated absences",
  "O que o aluno deve levar? (Ex: Bíblia, Caderno, Caneta)": "What should the student bring? (E.g.: Bible, Notebook, Pen)",
  "Visão consolidada de volume, produtividade e SLA.": "Consolidated view of volume, productivity and SLA.",
  "Visão detalhada da célula.": "Detailed cell view.",
  "Visão detalhada do curso.": "Detailed course view.",
  "Visão detalhada do evento.": "Detailed event view.",
  "Regra de Responsáveis": "Responsibles Rule",
  "(Regra de 1 responsável a cada 30 vagas).": "(Rule of 1 responsible per 30 spots).",
  "Adicione regras para exportar apenas os dados que você precisa.": "Add rules to export only the data you need.",
  "Adicione informações adicionais, observações importantes ou orientações...": "Add additional information, important notes or guidelines...",
  "Verifique todas as configurações antes de gerar. O QR Code poderá ser baixado na próxima tela.": "Check all settings before generating. The QR Code can be downloaded on the next screen.",
  "Escaneie o código": "Scan the code",
  "Expira em": "Expires in",
  "Expira em 30 segundos": "Expires in 30 seconds",
  "Após expirar, é necessário gerar outro código para conseguir ler no WhatsApp.": "After it expires, you need to generate another code to read on WhatsApp.",
  "Finalidade": "Purpose",
  "1. Finalidade do QR Code": "1. QR Code Purpose",
  "Para qual situação este QR Code será usado?": "What situation will this QR Code be used for?",
  "Selecione a finalidade": "Select the purpose",
  "Automação iniciada via QR Code": "Automation started via QR Code",
  "Os dados inseridos no sistema são de responsabilidade da organização usuária.": "The data entered in the system is the responsibility of the user organization.",
  "Quer saber mais?": "Want to know more?",
  "Saiba mais": "Learn more",
  "Termos de Uso": "Terms of Use",
  "Termos de Uso e Serviço": "Terms of Use and Service",
  "Política de Privacidade": "Privacy Policy",
  "Termo de Responsabilidade": "Terms of Responsibility",
  "Documento Jurídico Oficial": "Official Legal Document",
  "Estou ciente e concordo": "I acknowledge and agree",
  "Continuar para Colunas": "Continue to Columns",
  "Continuar para Filtros": "Continue to Filters",
  "Continuar para Formato": "Continue to Format",
  "Passo 1: Fonte de Dados": "Step 1: Data Source",
  "Passo 2: Colunas para exportar": "Step 2: Columns to Export",
  "Passo 3: Filtros (Opcional)": "Step 3: Filters (Optional)",
  "Passo 4: Formato de Exportação": "Step 4: Export Format",
  "De onde as informações serão extraídas?": "Where will the information be extracted from?",
  "Se você não adicionar nenhuma regra, o sistema irá exportar todos os dados cadastrados neste módulo.": "If you don't add any rules, the system will export all registered data for this module.",
  "Os filtros servem para afunilar a sua busca.": "Filters are used to narrow down your search.",
  "Os relatórios antigos ficam disponíveis por 30 dias.": "Old reports are available for 30 days.",
  "Os relatórios gerados ficam disponíveis por 30 dias. Depois disso eles são excluídos permanentemente e será necessário gerá-los novamente.": "Generated reports are available for 30 days. After that they are permanently deleted and must be generated again.",
  "Revise os relatórios gerados anteriormente e faça o download novamente.": "Review previously generated reports and download them again.",
  "Como você deseja receber este relatório?": "How would you like to receive this report?",
  "Aqui estão os indicadores mais importantes da sua igreja hoje.": "Here are the most important indicators for your church today.",
  "Utilize o motor de extração para cruzar e exportar qualquer dado do sistema.": "Use the extraction engine to cross-reference and export any system data.",
  "Utilize o motor de extração para cruzar e exportar qualquer dado do HelpDesk.": "Use the extraction engine to cross-reference and export any HelpDesk data.",
  "Não lidas": "Unread",
  "Não lidos": "Unread",
  "Aguardando": "Waiting",
  "Aguardando leitura": "Awaiting reading",
  "Aguardando retorno": "Awaiting reply",
  "Em atendimento": "In service",
  "em andamento": "in progress",
  "em espera": "on hold",
  "Em funcionamento": "In operation",
  "Estourado": "Exceeded",
  "Dentro do prazo": "Within deadline",
  "No Prazo": "On Time",
  "Fora do prazo": "Past deadline",
  "Urgente": "Urgent",
  "Alta": "High",
  "Prioridade Alta": "High Priority",
  "Prioridade:": "Priority:",
  "Prazo": "Deadline",
  "Tempo SLA": "SLA Time",
  "SLA:": "SLA:",
  "TMA (Média)": "TMA (Average)",
  "TMA vs TMR": "TMA vs TMR",
  "TMR (Resposta)": "TMR (Response)",
  "Tempo médio de resposta": "Average response time",
  "Maior taxa de resposta": "Highest response rate",
  "Taxa Resp.": "Resp. Rate",
  "Resp.": "Resp.",
  "Volume Diário": "Daily Volume",
  "Setor / Fila:": "Sector / Queue:",
  "Consolidados: 32": "Consolidated: 32",
  "3 atenção": "3 attention",
  "Desligamento": "Deactivation",
  "Motivo do desligamento *": "Reason for deactivation *",
  "Descreva o motivo do desligamento...": "Describe the reason for deactivation...",
  "O motivo deve ter no mínimo 10 caracteres.": "The reason must be at least 10 characters.",
  "Mínimo de 10 caracteres": "Minimum 10 characters",
  "Mínimo de 8 caracteres": "Minimum 8 characters",
  "Use pelo menos 8 caracteres para uma senha mais segura. Mantenha suas credenciais sempre protegidas.": "Use at least 8 characters for a stronger password. Keep your credentials protected at all times.",
  "Mínimo de 10 caracteres": "Minimum 10 characters",
  "Essa ação removerá a pessoa da lista de visitantes, criará um cadastro em Membros e registrará toda a transição no histórico permanente.": "This action will remove the person from the visitors list, create a record in Members and log the entire transition in the permanent history.",
  "Converter para membro": "Convert to member",
  "Mover de categoria": "Move from category",
  "Marcar como pendente": "Mark as pending",
  "Digite a descrição da célula": "Enter the cell description",
  "Digite a descrição do perfil": "Enter the profile description",
  "Digite a pergunta...": "Type the question...",
  "Digite o nome da rede": "Enter the network name",
  "Digite o nome do ministério": "Enter the ministry name",
  "Digite o valor...": "Enter the value...",
  "Digite uma resposta...": "Type an answer...",
  "Defina até 4 opções de resposta (mínimo 2)": "Define up to 4 answer options (minimum 2)",
  "Perguntas do formulário": "Form questions",
  "Pergunta": "Question",
  "Perguntas adicionais bloqueadas": "Additional locked questions",
  "Qual campo?": "Which field?",
  "Qual evento/curso?": "Which event/course?",
  "Qual igreja?": "Which church?",
  "Condição...": "Condition...",
  "Igual a": "Equals",
  "Diferente de": "Different from",
  "Maior ou igual a": "Greater than or equal to",
  "Contém": "Contains",
  "Começa com": "Starts with",
  "Começa com / Termina com": "Starts with / Ends with",
  "Está vazio": "Is empty",
  "Está vazio / Não está vazio": "Is empty / Is not empty",
  "Intervalo": "Range",
  "Busca o valor exato, sem tirar nem pôr.": "Searches for the exact value.",
  "Busca registros que tenham essa palavra em qualquer parte do texto.": "Searches for records containing this word anywhere in the text.",
  "Busca textos que iniciem ou terminem com as letras que você informar.": "Searches for texts that start or end with the letters you provide.",
  "Ideal para valores numéricos ou datas.": "Ideal for numeric values or dates.",
  "Verifica se o campo foi preenchido ou deixado em branco no cadastro.": "Checks if the field was filled or left blank during registration.",
  "Entenda cada opção para extrair dados precisos": "Understand each option to extract precise data",
  "Entendendo as Regras (Operadores)": "Understanding Rules (Operators)",
  "Como usar os Filtros?": "How to use Filters?",
  "Entendi": "Understood",
  "Entendi, fechar": "Understood, close",
  "Exemplo:": "Example:",
  "Ex: 10": "E.g.: 10",
  "Ex: 12 (opcional)": "E.g.: 12 (optional)",
  "Ex: 32": "E.g.: 32",
  "Ex: 50": "E.g.: 50",
  "Ex: Acampamento Jovem": "E.g.: Youth Camp",
  "Ex: Apto 42": "E.g.: Apt 42",
  "Ex: Av. Paulista": "E.g.: 5th Avenue",
  "Ex: Bela Vista": "E.g.: Downtown",
  "Ex: Como você nos conheceu?": "E.g.: How did you find us?",
  "Ex: Culto da Família...": "E.g.: Family Worship...",
  "Ex: Curso de Liderança Avançada": "E.g.: Advanced Leadership Course",
  "Ex: Engenheiro": "E.g.: Engineer",
  "Ex: Eventos e Convites": "E.g.: Events and Invitations",
  "Ex: Família e Fé": "E.g.: Family and Faith",
  "Ex: João da Silva": "E.g.: John Doe",
  "Ex: Pastor João Silva": "E.g.: Pastor John Doe",
  "Ex: Apto 101, Sala 2": "E.g.: Apt 101, Room 2",
  "Ex.: Pastor, Obreiro...": "E.g.: Pastor, Worker...",
  "1. Escolha seu plano": "1. Choose your plan",
  "1. Informações Básicas do Curso": "1. Basic Course Information",
  "1. Informações Básicas do Evento": "1. Basic Event Information",
  "2. Campos Padrão (Obrigatórios)": "2. Default Fields (Required)",
  "2. Localização e Estrutura": "2. Location and Structure",
  "3. Dinâmica, Aulas e Conclusão": "3. Dynamics, Classes and Completion",
  "3. Forma de pagamento": "3. Payment method",
  "3. Perguntas Extras": "3. Extra Questions",
  "4. Dados do cartão": "4. Card data",
  "4. Material de Apoio (Automação)": "4. Support Material (Automation)",
  "4. Responsáveis pela Turma": "4. Class Responsibles",
  "4. Responsáveis pelo Evento": "4. Event Responsibles",
  "5. Notificações": "5. Notifications",
  "Opções": "Options",
  "Múltipla Escolha (Botões)": "Multiple Choice (Buttons)",
  "Resposta em Texto Livre": "Free Text Response",
  "Respostas Inteligentes": "Smart Responses",
  "Respostas recebidas": "Received responses",
  "Texto da Pergunta": "Question Text",
  "Obrigatória": "Required",
  "Tipo de Resposta": "Answer Type",
  "Tipo de resposta": "Answer type",
  "Pergunta": "Question",
  "Sem filtros aplicados": "No filters applied",
  "Tente buscar com outros termos.": "Try searching with other terms.",
  "Tente buscar por outras finalidades ou crie um novo.": "Try searching for other purposes or create a new one.",
  "Tente buscar por outro termo.": "Try searching for another term.",
  "Por favor, selecione": "Please select",
  "Por favor, aguarde": "Please wait",
  "Você deve fazer o upload do seu material em uma nuvem (Google Drive, Dropbox, etc.) e": "You must upload your material to a cloud service (Google Drive, Dropbox, etc.) and",
  "colar o link de acesso": "paste the access link",
  "no campo indicado. O link será disparado aos alunos matriculados.": "in the indicated field. The link will be sent to enrolled students.",
  "não armazena arquivos pesados": "does not store heavy files",
  "como PDFs ou Apostilas em nossos servidores.": "such as PDFs or Workbooks on our servers.",
  "A plataforma": "The platform",
  "O sistema Basiléia é disponibilizado como ferramenta de apoio à gestão e comunicação, não sendo garantido qualquer resultado específico decorrente de sua utilização.": "The Basiléia system is made available as a management and communication support tool, and no specific result from its use is guaranteed.",
  "Responsável": "Responsible",
  "Responsabilizar-se pelos dados inseridos na plataforma.": "Take responsibility for the data entered in the platform.",
  "Solicitante": "Requester",
  "Assunto": "Subject",
  "Motivo": "Reason",
  "Origem:": "Origin:",
  "Papel": "Role",
  "Nível": "Level",
  "Nível de Acesso": "Access Level",
  "Módulo": "Module",
  "Categoria": "Category",
  "Anexar Arquivo": "Attach File",
  "Encontros": "Meetings",
  "encontro": "meeting",
  "Encontro": "Meeting",
  "Dia da semana": "Weekday",
  "Dia do Evento": "Event Day",
  "Dom": "Sun",
  "Seg": "Mon",
  "Ter": "Tue",
  "Qua": "Wed",
  "Qui": "Thu",
  "Sex": "Fri",
  "Sáb": "Sat",
  "Manhã": "Morning",
  "Tarde": "Afternoon",
  "Noite": "Night",
  "Madrugada": "Dawn",
  "Janeiro": "January",
  "Fevereiro": "February",
  "Março": "March",
  "Abril": "April",
  "Maio": "May",
  "Junho": "June",
  "Julho": "July",
  "Agosto": "August",
  "Setembro": "September",
  "Outubro": "October",
  "Novembro": "November",
  "Dezembro": "December",
  "Mês": "Month",
  "Meses": "Months",
  "Ano": "Year",
  "Hoje": "Today",
  "Ontem": "Yesterday",
  "Amanhã": "Tomorrow",
  "Esses dados ajudam sua equipe a acompanhar cada decisão e cuidar de cada nova vida com agilidade.": "This data helps your team track each decision and care for each new life with agility.",
  "Mantenha o acompanhamento": "Keep following up",
  "Como conheceu a igreja?": "How did you find the church?",
  "Descreva brevemente como o visitante chegou até a igreja...": "Briefly describe how the visitor found the church...",
  "Veio de outra igreja?": "Came from another church?",
  "Nome da igreja anterior": "Previous church name",
  "Reconciliou com Jesus?": "Reconciled with Jesus?",
  "Tempo igreja": "Time in church",
  "Espiar": "Preview",
  "Construtor Dinâmico": "Dynamic Builder",
  "Fim": "End",
  "Início": "Start",
  "Seguinte": "Next",
  "Último": "Last",
  "Primeiro": "First",
  "Anterior": "Previous",
  "Norte": "North",
  "Sul": "South",
  "Leste": "East",
  "Oeste": "West",
  "Centro": "Center",
  "adicional": "additional",
  "sem telefone informado": "no phone provided",
  "dd/mm/aaaa": "mm/dd/yyyy",
  "hh:mm": "hh:mm",
  "1 a 5": "1 to 5",
  "1 sem conexão há 2h": "1 without connection for 2h",
  "1.148 de 1.800 msgs": "1,148 of 1,800 msgs",
  "12m": "12mo",
  "2.5m": "2.5mo",
  "18. Trará apenas maiores de idade.": "18. Will only bring adults.",
  "3 min": "3 min",
  "4a 2m": "4yr 2mo",
  "5 neste fim de semana": "5 this weekend",
  "6 sem contato": "6 without contact",
  "+3 esse mês": "+3 this month",
  "+ Adicionar minha primeira regra": "+ Add my first rule",
  "+ Informações Relevantes": "+ Relevant Information",
  "(opcional)": "(optional)",
  "&gt;": "&gt;",
  "&lt;": "&lt;",
  "Selecione o plano ideal conforme a quantidade de membros da sua igreja e finalize a atualização do plano.": "Select the ideal plan according to your church size and finalize the plan update.",
  "Clique no botão \"Novo horário\" para adicionar cultos à agenda.": "Click the \"New time\" button to add worship services to the schedule.",
  "2. Campos Padrão (Obrigatórios)": "2. Default Fields (Required)",
  "Os campos abaixo são exigidos por padrão no formulário gerado pelo QR Code.": "The fields below are required by default in the form generated by the QR Code.",
  "Para Eventos e Cursos, o QR Code exige apenas os dados padrão (Nome e Telefone) para agilizar o processo de inscrição.": "For Events and Courses, the QR Code requires only standard data (Name and Phone) to speed up the enrollment process.",
  "Esta aba contém os mesmos campos da tela de \"Novo Curso\", com os dados já preenchidos.": "This tab contains the same fields as the \"New Course\" screen, with data already filled in.",
  "Esta aba contém os mesmos campos da tela de \"Novo Evento\", com os dados já preenchidos.": "This tab contains the same fields as the \"New Event\" screen, with data already filled in.",
  "💡 Note: Esta aba carrega os mesmos campos de `Nova Célula`, preenchidos! (Omitidos aqui por brevidade).": "💡 Note: This tab loads the same fields as `New Cell`, pre-filled! (Omitted here for brevity).",
  "Ao finalizar o formulário, o sistema enviará automaticamente este material para o contato preenchido.": "When the form is completed, the system will automatically send this material to the contact provided.",
  "1.148 de 1.800 msgs": "1,148 of 1,800 msgs",
  "de 1.800 disp.": "of 1,800 available",
  "do total": "of total",
  "até": "to",
  "em um": "in one",
  "ou": "or",
  "e": "and",
  "Rua 2300": "2300 Street",
  "Balneário Camboriú": "Balneário Camboriú",
  "Todas as conversas do WhatsApp do número único são distribuídas automaticamente entre os atendentes.": "All WhatsApp conversations from the single number are automatically distributed among attendants.",
  "Pessoa": "Person",
  "Pessoas": "People",
  "Membros por Célula (GC)": "Members per Cell (CG)",
  "Projetos Sociais": "Social Projects",
  "Propósito": "Purpose",
  "Base Bíblica": "Biblical Basis",
  "Conexões": "Connections",
  "Sexta-feira às 19:30": "Friday at 7:30 PM",
  "Possui Kids?": "Has Kids?",
  "Possui estacionamento?": "Has parking?",
  "Apenas casados?": "Only married?",
  "Média": "Average",
  "Máximo": "Maximum",
  "Mínimo": "Minimum",
  "Clique para editar": "Click to edit",
  "Arraste para reordenar": "Drag to reorder",
  "R3-GC-BC- RUA 3300": "CG3-BC- 3300 STREET",
  "Encerrar": "Close",
  "Encerramento Previsto": "Expected Closure",
  "Inativa": "Inactive",
  "Ativa": "Active",
  "Total de instâncias": "Total instances",
  "Conta Pessoal": "Personal Account",
  "Novo registro": "New record",
  "Período de Referência": "Reference Period",
  "Louvor": "Worship",
  "Pregador(a)": "Preacher",
  "Data do evento": "Event date",
  "Data do encontro": "Meeting date",
  "Presença média": "Average attendance",
  "1.148 de 1.800 msgs": "1,148 of 1,800 msgs",
  "Mensagens hoje": "Today's messages",
  "Quantidade de membros no culto": "Number of members at worship",
  "Quantos visitantes?": "How many visitors?",
  "Escreva observações sobre o culto (ambiente, louvor, oferta, testemunhos, visitantes, etc.)": "Write observations about the service (atmosphere, worship, offering, testimonies, visitors, etc.)",
  "Preencha as informações abaixo para registrar a presença no culto.": "Fill in the information below to record worship attendance.",
  "Violação e Cumprimento de SLA por Fila": "SLA Violation and Compliance by Queue",
  "Última atividade": "Last activity",
  "Última atualização: Junho de 2026": "Last updated: June 2026",
  "Última msg:": "Last msg:",
  "Últimas 12 semanas": "Last 12 weeks",
  "Último ano": "Last year",
  "Último contato:": "Last contact:",
  "Últimos 30 dias": "Last 30 days",
  "Últimos 6 meses": "Last 6 months",
  "Últimos relatórios": "Latest reports",
  "⌘K": "⌘K",
};

const PT_ES = {
  "GESTÃO": "GESTIÓN",
  "CUIDADOS": "CUIDADOS",
  "CONFIGURAÇÕES": "CONFIGURACIONES",
  "Configurações": "Configuraciones",
  "Administrador": "Administrador",
  "Dashboard": "Panel",
  "Membros": "Miembros",
  "Membro": "Miembro",
  "Membro Ativo": "Miembro Activo",
  "Novo membro": "Nuevo miembro",
  "Editar membro": "Editar miembro",
  "Buscar membro...": "Buscar miembro...",
  "Importar membro": "Importar miembro",
  "Células": "Células",
  "Célula": "Célula",
  "Nova célula": "Nueva célula",
  "Cursos": "Cursos",
  "Curso": "Curso",
  "Eventos": "Eventos",
  "Evento": "Evento",
  "Atendimentos": "Atenciones",
  "Relatórios": "Informes",
  "Relatório": "Informe",
  "Usuários": "Usuarios",
  "Perfil": "Perfil",
  "Igreja": "Iglesia",
  "Nome da igreja": "Nombre de la iglesia",
  "Pastor": "Pastor",
  "Líder": "Líder",
  "Liderança": "Liderazgo",
  "Visitante": "Visitante",
  "Visitantes": "Visitantes",
  "Ministério": "Ministerio",
  "Ministérios": "Ministerios",
  "Rede": "Red",
  "Redes": "Redes",
  "Nova rede": "Nueva red",
  "Culto": "Culto",
  "Cultos": "Cultos",
  "Agenda de Cultos": "Agenda de Cultos",
  "Nome": "Nombre",
  "Nome completo": "Nombre completo",
  "E-mail": "Correo electrónico",
  "Telefone": "Teléfono",
  "Celular / Recado": "Celular / Recado",
  "Endereço": "Dirección",
  "Endereço Completo": "Dirección Completa",
  "Cidade": "Ciudad",
  "Estado": "Estado",
  "País": "País",
  "Bairro": "Barrio",
  "CEP": "Código Postal",
  "Rua": "Calle",
  "Número": "Número",
  "Complemento": "Complemento",
  "Data": "Fecha",
  "Data de nascimento": "Fecha de nacimiento",
  "Data de início": "Fecha de inicio",
  "Horário": "Horario",
  "Status": "Estado",
  "Ativo": "Activo",
  "Inativo": "Inactivo",
  "Tipo": "Tipo",
  "Categoria": "Categoría",
  "Categorias": "Categorías",
  "Descrição": "Descripción",
  "Observações": "Observaciones",
  "Editar": "Editar",
  "Buscar": "Buscar",
  "Pesquisar...": "Buscar...",
  "Adicionar": "Agregar",
  "Novo": "Nuevo",
  "Novo Curso": "Nuevo Curso",
  "Novo Evento": "Nuevo Evento",
  "Remover": "Eliminar",
  "Excluir": "Eliminar",
  "Fechar": "Cerrar",
  "Voltar": "Volver",
  "Próximo": "Siguiente",
  "Próxima": "Siguiente",
  "Anterior": "Anterior",
  "Confirmar": "Confirmar",
  "Salvar": "Guardar",
  "Salvar alterações": "Guardar cambios",
  "Cancelar": "Cancelar",
  "Carregando...": "Cargando...",
  "Erro": "Error",
  "Sucesso": "Éxito",
  "Atenção:": "Atención:",
  "Informações Básicas": "Información Básica",
  "Informações Adicionais": "Información Adicional",
  "Nenhum resultado encontrado": "No se encontraron resultados",
  "Nenhum registro encontrado": "No se encontraron registros",
  "Selecione": "Seleccione",
  "Ações": "Acciones",
  "Ação": "Acción",
  "Total": "Total",
  "Limpar": "Limpiar",
  "Filtrar": "Filtrar",
  "Aplicar": "Aplicar",
  "Exportar": "Exportar",
  "Importar": "Importar",
  "Enviar": "Enviar",
  "Senha": "Contraseña",
  "Nova senha": "Nueva contraseña",
  "Cargo": "Cargo",
  "Cargos": "Cargos",
  "Função": "Función",
  "Cadastros": "Registros",
  "Contato": "Contacto",
  "Assistente Virtual": "Asistente Virtual",
  "QR Code": "Código QR",
  "QR Codes": "Códigos QR",
  "Notificação": "Notificación",
  "Configurações do Sistema": "Configuraciones del Sistema",
  "Central de atendimento": "Centro de atención",
  "Controle de Presença": "Control de Asistencia",
  "Registro de Presença": "Registro de Asistencia",
  "Copyright © 2026 Basiléia, Todos os direitos reservados": "Copyright © 2026 Basiléia, Todos los derechos reservados",
  ", Todos os direitos reservados": ", Todos los derechos reservados",
  "Gerenciamento de Células": "Gestión de Células",
  "Aceitou Jesus": "Aceptó a Jesús",
  "Batismo": "Bautismo",
  "Batizado?": "¿Bautizado?",
  "Data do batismo": "Fecha del bautismo",
  "Oração": "Oración",
  "Idioma": "Idioma",
  "Língua preferida": "Idioma preferido",
  "Sexo": "Sexo",
  "Masculino": "Masculino",
  "Feminino": "Femenino",
  "Estado civil": "Estado civil",
  "Casado?": "¿Casado?",
  "Nacionalidade": "Nacionalidad",
  "Escolaridade": "Escolaridad",
  "Profissão": "Profesión",
  "Documento (CPF/RG)": "Documento (CPF/RG)",
  "Moeda": "Moneda",
  "Fuso horário": "Zona horaria",
  "Página": "Página",
  "Linhas por página": "Filas por página",
  "Mostrando": "Mostrando",
  "País": "País",
  "Copyright © 2026": "Copyright © 2026",
  "Sim": "Sí",
  "Não": "No",
  "Todos": "Todos",
  "Converter para membro": "Convertir a miembro",
  "Detalhes": "Detalles",
};

const PT_FR = {
  "GESTÃO": "GESTION",
  "CUIDADOS": "SOINS",
  "CONFIGURAÇÕES": "CONFIGURATIONS",
  "Configurações": "Paramètres",
  "Administrador": "Administrateur",
  "Dashboard": "Tableau de bord",
  "Membros": "Membres",
  "Membro": "Membre",
  "Membro Ativo": "Membre Actif",
  "Novo membro": "Nouveau membre",
  "Editar membro": "Modifier le membre",
  "Buscar membro...": "Rechercher un membre...",
  "Importar membro": "Importer un membre",
  "Células": "Cellules",
  "Célula": "Cellule",
  "Nova célula": "Nouvelle cellule",
  "Cursos": "Cours",
  "Curso": "Cours",
  "Eventos": "Événements",
  "Evento": "Événement",
  "Atendimentos": "Services",
  "Relatórios": "Rapports",
  "Relatório": "Rapport",
  "Usuários": "Utilisateurs",
  "Perfil": "Profil",
  "Igreja": "Église",
  "Nome da igreja": "Nom de l'église",
  "Pastor": "Pasteur",
  "Líder": "Leader",
  "Liderança": "Leadership",
  "Visitante": "Visiteur",
  "Visitantes": "Visiteurs",
  "Ministério": "Ministère",
  "Ministérios": "Ministères",
  "Rede": "Réseau",
  "Redes": "Réseaux",
  "Nova rede": "Nouveau réseau",
  "Culto": "Culte",
  "Cultos": "Cultes",
  "Agenda de Cultos": "Agenda des Cultes",
  "Nome": "Nom",
  "Nome completo": "Nom complet",
  "E-mail": "E-mail",
  "Telefone": "Téléphone",
  "Celular / Recado": "Mobile / Message",
  "Endereço": "Adresse",
  "Endereço Completo": "Adresse Complète",
  "Cidade": "Ville",
  "Estado": "État",
  "País": "Pays",
  "Bairro": "Quartier",
  "CEP": "Code Postal",
  "Rua": "Rue",
  "Número": "Numéro",
  "Complemento": "Complément",
  "Data": "Date",
  "Data de nascimento": "Date de naissance",
  "Data de início": "Date de début",
  "Horário": "Horaire",
  "Status": "Statut",
  "Ativo": "Actif",
  "Inativo": "Inactif",
  "Tipo": "Type",
  "Categoria": "Catégorie",
  "Categorias": "Catégories",
  "Descrição": "Description",
  "Observações": "Observations",
  "Editar": "Modifier",
  "Buscar": "Rechercher",
  "Pesquisar...": "Rechercher...",
  "Adicionar": "Ajouter",
  "Novo": "Nouveau",
  "Novo Curso": "Nouveau Cours",
  "Novo Evento": "Nouvel Événement",
  "Remover": "Supprimer",
  "Excluir": "Supprimer",
  "Fechar": "Fermer",
  "Voltar": "Retour",
  "Próximo": "Suivant",
  "Próxima": "Suivante",
  "Anterior": "Précédent",
  "Confirmar": "Confirmer",
  "Salvar": "Enregistrer",
  "Salvar alterações": "Enregistrer les modifications",
  "Cancelar": "Annuler",
  "Carregando...": "Chargement...",
  "Erro": "Erreur",
  "Sucesso": "Succès",
  "Atenção:": "Attention:",
  "Informações Básicas": "Informations de Base",
  "Informações Adicionais": "Informations Complémentaires",
  "Nenhum resultado encontrado": "Aucun résultat trouvé",
  "Nenhum registro encontrado": "Aucun enregistrement trouvé",
  "Selecione": "Sélectionnez",
  "Ações": "Actions",
  "Ação": "Action",
  "Total": "Total",
  "Limpar": "Effacer",
  "Filtrar": "Filtrer",
  "Aplicar": "Appliquer",
  "Exportar": "Exporter",
  "Importar": "Importer",
  "Enviar": "Envoyer",
  "Senha": "Mot de passe",
  "Nova senha": "Nouveau mot de passe",
  "Cargo": "Rôle",
  "Cargos": "Rôles",
  "Função": "Fonction",
  "Cadastros": "Registres",
  "Contato": "Contact",
  "Assistente Virtual": "Assistant Virtuel",
  "QR Code": "Code QR",
  "Notificação": "Notification",
  "Configurações do Sistema": "Paramètres Système",
  "Central de atendimento": "Centre d'assistance",
  "Controle de Presença": "Contrôle de Présence",
  "Registro de Presença": "Registre de Présence",
  "Gerenciamento de Células": "Gestion des Cellules",
  "Aceitou Jesus": "Accepté Jésus",
  "Batismo": "Baptême",
  "Batizado?": "Baptisé?",
  "Data do batismo": "Date du baptême",
  "Oração": "Prière",
  "Idioma": "Langue",
  "Língua preferida": "Langue préférée",
  "Sexo": "Sexe",
  "Masculino": "Masculin",
  "Feminino": "Féminin",
  "Estado civil": "État civil",
  "Casado?": "Marié?",
  "Nacionalidade": "Nationalité",
  "Escolaridade": "Niveau d'études",
  "Profissão": "Profession",
  "Documento (CPF/RG)": "Document (CPF/RG)",
  "Moeda": "Monnaie",
  "Fuso horário": "Fuseau horaire",
  "Página": "Page",
  "Linhas por página": "Lignes par page",
  "Mostrando": "Affichage",
  "Sim": "Oui",
  "Não": "Non",
  "Todos": "Tous",
  "Converter para membro": "Convertir en membre",
};

const PT_DE = {
  "GESTÃO": "VERWALTUNG",
  "CUIDADOS": "FÜRSORGE",
  "CONFIGURAÇÕES": "EINSTELLUNGEN",
  "Configurações": "Einstellungen",
  "Administrador": "Administrator",
  "Dashboard": "Dashboard",
  "Membros": "Mitglieder",
  "Membro": "Mitglied",
  "Membro Ativo": "Aktives Mitglied",
  "Novo membro": "Neues Mitglied",
  "Editar membro": "Mitglied bearbeiten",
  "Buscar membro...": "Mitglied suchen...",
  "Importar membro": "Mitglied importieren",
  "Células": "Zellen",
  "Célula": "Zelle",
  "Nova célula": "Neue Zelle",
  "Cursos": "Kurse",
  "Curso": "Kurs",
  "Eventos": "Veranstaltungen",
  "Evento": "Veranstaltung",
  "Atendimentos": "Dienste",
  "Relatórios": "Berichte",
  "Relatório": "Bericht",
  "Usuários": "Benutzer",
  "Perfil": "Profil",
  "Igreja": "Kirche",
  "Nome da igreja": "Name der Kirche",
  "Pastor": "Pastor",
  "Líder": "Leiter",
  "Liderança": "Leiterschaft",
  "Visitante": "Besucher",
  "Visitantes": "Besucher",
  "Ministério": "Dienst",
  "Ministérios": "Dienste",
  "Rede": "Netzwerk",
  "Redes": "Netzwerke",
  "Nova rede": "Neues Netzwerk",
  "Culto": "Gottesdienst",
  "Cultos": "Gottesdienste",
  "Agenda de Cultos": "Gottesdienstplan",
  "Nome": "Name",
  "Nome completo": "Vollständiger Name",
  "E-mail": "E-Mail",
  "Telefone": "Telefon",
  "Celular / Recado": "Mobil / Nachricht",
  "Endereço": "Adresse",
  "Endereço Completo": "Vollständige Adresse",
  "Cidade": "Stadt",
  "Estado": "Bundesland",
  "País": "Land",
  "Bairro": "Stadtteil",
  "CEP": "PLZ",
  "Rua": "Straße",
  "Número": "Nummer",
  "Complemento": "Zusatz",
  "Data": "Datum",
  "Data de nascimento": "Geburtsdatum",
  "Data de início": "Startdatum",
  "Horário": "Zeit",
  "Status": "Status",
  "Ativo": "Aktiv",
  "Inativo": "Inaktiv",
  "Tipo": "Typ",
  "Categoria": "Kategorie",
  "Categorias": "Kategorien",
  "Descrição": "Beschreibung",
  "Observações": "Bemerkungen",
  "Editar": "Bearbeiten",
  "Buscar": "Suchen",
  "Pesquisar...": "Suchen...",
  "Adicionar": "Hinzufügen",
  "Novo": "Neu",
  "Novo Curso": "Neuer Kurs",
  "Novo Evento": "Neue Veranstaltung",
  "Remover": "Entfernen",
  "Excluir": "Löschen",
  "Fechar": "Schließen",
  "Voltar": "Zurück",
  "Próximo": "Weiter",
  "Próxima": "Weiter",
  "Anterior": "Zurück",
  "Confirmar": "Bestätigen",
  "Salvar": "Speichern",
  "Salvar alterações": "Änderungen speichern",
  "Cancelar": "Abbrechen",
  "Carregando...": "Lädt...",
  "Erro": "Fehler",
  "Sucesso": "Erfolg",
  "Atenção:": "Achtung:",
  "Informações Básicas": "Basisinformationen",
  "Informações Adicionais": "Zusätzliche Informationen",
  "Nenhum resultado encontrado": "Keine Ergebnisse gefunden",
  "Nenhum registro encontrado": "Keine Einträge gefunden",
  "Selecione": "Auswählen",
  "Ações": "Aktionen",
  "Ação": "Aktion",
  "Total": "Gesamt",
  "Limpar": "Löschen",
  "Filtrar": "Filtern",
  "Aplicar": "Anwenden",
  "Exportar": "Exportieren",
  "Importar": "Importieren",
  "Enviar": "Senden",
  "Senha": "Passwort",
  "Nova senha": "Neues Passwort",
  "Cargo": "Rolle",
  "Cargos": "Rollen",
  "Função": "Funktion",
  "Cadastros": "Register",
  "Contato": "Kontakt",
  "Assistente Virtual": "Virtueller Assistent",
  "QR Code": "QR-Code",
  "Notificação": "Benachrichtigung",
  "Configurações do Sistema": "Systemeinstellungen",
  "Central de atendimento": "Service-Center",
  "Controle de Presença": "Anwesenheitskontrolle",
  "Registro de Presença": "Anwesenheitsliste",
  "Gerenciamento de Células": "Zellenverwaltung",
  "Aceitou Jesus": "Jesus angenommen",
  "Batismo": "Taufe",
  "Batizado?": "Getauft?",
  "Data do batismo": "Taufdatum",
  "Oração": "Gebet",
  "Idioma": "Sprache",
  "Língua preferida": "Bevorzugte Sprache",
  "Sexo": "Geschlecht",
  "Masculino": "Männlich",
  "Feminino": "Weiblich",
  "Estado civil": "Familienstand",
  "Casado?": "Verheiratet?",
  "Nacionalidade": "Nationalität",
  "Escolaridade": "Bildung",
  "Profissão": "Beruf",
  "Moeda": "Währung",
  "Fuso horário": "Zeitzone",
  "Página": "Seite",
  "Linhas por página": "Zeilen pro Seite",
  "Mostrando": "Angezeigt",
  "Sim": "Ja",
  "Não": "Nein",
  "Todos": "Alle",
  "Converter para membro": "In Mitglied umwandeln",
  "Copyright © 2026": "Copyright © 2026",
  ", Todos os direitos reservados": ", Alle Rechte vorbehalten",
};

const PT_IT = {
  "GESTÃO": "GESTIONE",
  "CUIDADOS": "CURE",
  "CONFIGURAÇÕES": "IMPOSTAZIONI",
  "Configurações": "Impostazioni",
  "Administrador": "Amministratore",
  "Dashboard": "Dashboard",
  "Membros": "Membri",
  "Membro": "Membro",
  "Membro Ativo": "Membro Attivo",
  "Novo membro": "Nuovo membro",
  "Editar membro": "Modifica membro",
  "Buscar membro...": "Cerca membro...",
  "Importar membro": "Importa membro",
  "Células": "Cellule",
  "Célula": "Cellula",
  "Nova célula": "Nuova cellula",
  "Cursos": "Corsi",
  "Curso": "Corso",
  "Eventos": "Eventi",
  "Evento": "Evento",
  "Atendimentos": "Assistenze",
  "Relatórios": "Report",
  "Relatório": "Report",
  "Usuários": "Utenti",
  "Perfil": "Profilo",
  "Igreja": "Chiesa",
  "Nome da igreja": "Nome della chiesa",
  "Pastor": "Pastore",
  "Líder": "Leader",
  "Liderança": "Leadership",
  "Visitante": "Visitatore",
  "Visitantes": "Visitatori",
  "Ministério": "Ministero",
  "Ministérios": "Ministeri",
  "Rede": "Rete",
  "Redes": "Reti",
  "Nova rede": "Nuova rete",
  "Culto": "Culto",
  "Cultos": "Culti",
  "Agenda de Cultos": "Programma dei Culti",
  "Nome": "Nome",
  "Nome completo": "Nome completo",
  "E-mail": "Email",
  "Telefone": "Telefono",
  "Celular / Recado": "Cellulare / Messaggio",
  "Endereço": "Indirizzo",
  "Endereço Completo": "Indirizzo Completo",
  "Cidade": "Città",
  "Estado": "Stato",
  "País": "Paese",
  "Bairro": "Quartiere",
  "CEP": "CAP",
  "Rua": "Via",
  "Número": "Numero",
  "Complemento": "Complemento",
  "Data": "Data",
  "Data de nascimento": "Data di nascita",
  "Data de início": "Data d'inizio",
  "Horário": "Orario",
  "Status": "Stato",
  "Ativo": "Attivo",
  "Inativo": "Inattivo",
  "Tipo": "Tipo",
  "Categoria": "Categoria",
  "Categorias": "Categorie",
  "Descrição": "Descrizione",
  "Observações": "Osservazioni",
  "Editar": "Modifica",
  "Buscar": "Cerca",
  "Pesquisar...": "Cerca...",
  "Adicionar": "Aggiungi",
  "Novo": "Nuovo",
  "Novo Curso": "Nuovo Corso",
  "Novo Evento": "Nuovo Evento",
  "Remover": "Rimuovi",
  "Excluir": "Elimina",
  "Fechar": "Chiudi",
  "Voltar": "Indietro",
  "Próximo": "Successivo",
  "Próxima": "Successiva",
  "Anterior": "Precedente",
  "Confirmar": "Conferma",
  "Salvar": "Salva",
  "Salvar alterações": "Salva modifiche",
  "Cancelar": "Annulla",
  "Carregando...": "Caricamento...",
  "Erro": "Errore",
  "Sucesso": "Successo",
  "Atenção:": "Attenzione:",
  "Informações Básicas": "Informazioni di Base",
  "Informações Adicionais": "Informazioni Aggiuntive",
  "Nenhum resultado encontrado": "Nessun risultato trovato",
  "Nenhum registro encontrado": "Nessun record trovato",
  "Selecione": "Seleziona",
  "Ações": "Azioni",
  "Ação": "Azione",
  "Total": "Totale",
  "Limpar": "Pulisci",
  "Filtrar": "Filtra",
  "Aplicar": "Applica",
  "Exportar": "Esporta",
  "Importar": "Importa",
  "Enviar": "Invia",
  "Senha": "Password",
  "Nova senha": "Nuova password",
  "Cargo": "Ruolo",
  "Cargos": "Ruoli",
  "Função": "Funzione",
  "Cadastros": "Registri",
  "Contato": "Contatto",
  "Assistente Virtual": "Assistente Virtuale",
  "QR Code": "Codice QR",
  "Notificação": "Notifica",
  "Configurações do Sistema": "Impostazioni di Sistema",
  "Central de atendimento": "Centro assistenza",
  "Controle de Presença": "Controllo Presenze",
  "Registro de Presença": "Registro Presenze",
  "Gerenciamento de Células": "Gestione Cellule",
  "Aceitou Jesus": "Accettato Gesù",
  "Batismo": "Battesimo",
  "Batizado?": "Battezzato?",
  "Data do batismo": "Data del battesimo",
  "Oração": "Preghiera",
  "Idioma": "Lingua",
  "Língua preferida": "Lingua preferita",
  "Sexo": "Sesso",
  "Masculino": "Maschile",
  "Feminino": "Femminile",
  "Estado civil": "Stato civile",
  "Casado?": "Sposato?",
  "Nacionalidade": "Nazionalità",
  "Escolaridade": "Istruzione",
  "Profissão": "Professione",
  "Moeda": "Valuta",
  "Fuso horário": "Fuso orario",
  "Página": "Pagina",
  "Linhas por página": "Righe per pagina",
  "Mostrando": "Mostrando",
  "Sim": "Sì",
  "Não": "No",
  "Todos": "Tutti",
  "Converter para membro": "Converti in membro",
  "Copyright © 2026": "Copyright © 2026",
  ", Todos os direitos reservados": ", Tutti i diritti riservati",
};

const DICTIONARIES = { en: PT_EN, es: PT_ES, fr: PT_FR, de: PT_DE, it: PT_IT };

const entityMap = {
  "&amp;": "&",
  "&lt;": "<",
  "&gt;": ">",
  "&quot;": "\"",
  "&#39;": "'",
  "&raquo;": "»",
  "&laquo;": "«",
  "&rarr;": "→",
  "&mdash;": "—",
  "&ndash;": "–",
};

function decodeEntities(str) {
  return str.replace(/&(?:amp|lt|gt|quot|#39|raquo|laquo|rarr|mdash|ndash);/g, (m) => entityMap[m] || m);
}

function translate(ptBr, langCode, keys) {
  const dict = DICTIONARIES[langCode];
  if (!dict) return null;

  const result = {};
  for (const key of keys) {
    const val = ptBr[key];
    if (dict.hasOwnProperty(val)) {
      result[key] = dict[val];
    } else {
      result[key] = val;
    }
  }
  return result;
}

async function main() {
  const args = process.argv.slice(2);
  const useAPI = args.includes("--api");
  const force = args.includes("--force");

  const ptBr = JSON.parse(fs.readFileSync(PT_BR_PATH, "utf-8"));
  const keys = Object.keys(ptBr);

  const total = LANGUAGES.length;
  let processed = 0;
  let skipped = 0;
  let updated = 0;
  let failed = 0;

  console.log(`Translate Engine — ${keys.length} keys, ${total} languages\n`);

  for (const lang of LANGUAGES) {
    if (lang.code === "pt-BR") continue;

    const filePath = path.join(SRC_DIR, `${lang.code}.json`);

    if (fs.existsSync(filePath) && !force) {
      processed++;
      skipped++;
      console.log(`[${processed}/${total - 1}] SKIP ${lang.code} (${lang.name}) — already exists`);
      continue;
    }

    processed++;
    console.log(`[${processed}/${total - 1}] Generating ${lang.code}.json (${lang.name})...`);

    try {
      let translations;

      if (DICTIONARIES[lang.code]) {
        translations = translate(ptBr, lang.code, keys);
      } else if (useAPI && API_URL) {
        const batchSize = 200;
        translations = {};

        for (let b = 0; b < keys.length; b += batchSize) {
          const batch = keys.slice(b, b + batchSize);
          const batchObj = {};
          batch.forEach((k) => { batchObj[k] = ptBr[k]; });

          process.stdout.write(`    Batch ${Math.floor(b / batchSize) + 1}/${Math.ceil(keys.length / batchSize)}... `);

          try {
            const systemMsg = `You are a translator. Translate the following Portuguese (Brazil) texts to ${lang.name}. Return ONLY a valid JSON object where keys are the original Portuguese texts and values are the translations. Do NOT include any other text, explanation, or markdown formatting.`;

            const response = await fetch(`${API_URL}/chat/completions`, {
              method: "POST",
              headers: {
                "Content-Type": "application/json",
                ...(API_KEY ? { Authorization: `Bearer ${API_KEY}` } : {}),
              },
              body: JSON.stringify({
                model: MODEL,
                messages: [
                  { role: "system", content: systemMsg },
                  { role: "user", content: JSON.stringify(batchObj, null, 2) },
                ],
                temperature: 0.1,
                max_tokens: 32000,
              }),
            });

            if (!response.ok) {
              const errText = await response.text();
              throw new Error(`API error ${response.status}: ${errText}`);
            }

            const data = await response.json();
            const content = data.choices?.[0]?.message?.content;
            if (!content) throw new Error("Empty API response");

            const jsonMatch = content.match(/\{[\s\S]*\}/);
            if (!jsonMatch) throw new Error("No JSON in response");

            const result = JSON.parse(jsonMatch[0]);
            Object.assign(translations, result);
            console.log("✓");

            if (b + batchSize < keys.length) {
              await new Promise((r) => setTimeout(r, 500));
            }
          } catch (err) {
            console.log(`✗ ${err.message.substring(0, 80)}`);
            for (const k of batch) translations[k] = ptBr[k];
          }
        }
      } else if (useAPI && !API_URL) {
        console.log(`    ⚠ API mode requires TRANSLATION_API_URL env var. Falling back to Portuguese.`);
        translations = {};
        for (const key of keys) translations[key] = ptBr[key];
      } else {
        translations = {};
        for (const key of keys) translations[key] = ptBr[key];
      }

      fs.writeFileSync(filePath, JSON.stringify(translations, null, 2), "utf-8");
      const dictInfo = DICTIONARIES[lang.code] ? ` (dictionary: ${Object.keys(DICTIONARIES[lang.code]).length} entries)` : "";
      console.log(`    ✓ Saved ${Object.keys(translations).length} keys${dictInfo}`);
      updated++;
    } catch (err) {
      console.log(`    ✗ FAILED: ${err.message}`);
      failed++;
    }
  }

  const dictTotal = Object.keys(DICTIONARIES.en).length +
    Object.keys(DICTIONARIES.es).length +
    Object.keys(DICTIONARIES.fr).length +
    Object.keys(DICTIONARIES.de).length +
    Object.keys(DICTIONARIES.it).length;

  console.log(`\nDone! ${updated} files updated, ${skipped} skipped, ${failed} failed.`);
  console.log(`Dictionary entries: EN=${Object.keys(DICTIONARIES.en).length}, ES=${Object.keys(DICTIONARIES.es).length}, FR=${Object.keys(DICTIONARIES.fr).length}, DE=${Object.keys(DICTIONARIES.de).length}, IT=${Object.keys(DICTIONARIES.it).length} (total: ${dictTotal})`);

  const totalAfter = fs.readdirSync(SRC_DIR).filter((f) => f.endsWith(".json")).length;
  console.log(`Total locale files: ${totalAfter}`);
}

main().catch(console.error);
